// Seed data (run this separately or move to a seed script file)
const seedProducts = [
  {
    name: 'Logitech G502 Mouse',
    price: 59.99,
    inStock: true,
    category: 'Tech',
    tags: ['electronics', 'peripherals'],
  },
  {
    name: 'Nike Air Zoom Pegasus',
    price: 120.0,
    inStock: true,
    category: 'Sportswear',
    tags: ['running', 'shoes'],
  },
  {
    name: 'Apple AirPods Pro',
    price: 249.0,
    inStock: true,
    category: 'Tech',
    tags: ['audio', 'wireless'],
  },
  {
    name: 'Adidas Soccer Ball',
    price: 35.0,
    inStock: true,
    category: 'Sports',
    tags: ['soccer', 'training'],
  },
  {
    name: 'Samsung Galaxy Watch 6',
    price: 329.99,
    inStock: true,
    category: 'Tech',
    tags: ['wearable', 'smartwatch'],
  },
  {
    name: 'Under Armour Duffle Bag',
    price: 45.0,
    inStock: true,
    category: 'Sportswear',
    tags: ['bag', 'gym'],
  },
  {
    name: 'ASUS ROG Gaming Laptop',
    price: 1499.99,
    inStock: false,
    category: 'Tech',
    tags: ['gaming', 'laptop'],
  },
  {
    name: 'Wilson Tennis Racket',
    price: 89.99,
    inStock: false,
    category: 'Sports',
    tags: ['tennis', 'equipment'],
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    price: 398.0,
    inStock: false,
    category: 'Tech',
    tags: ['audio', 'noise-cancelling'],
  },
  {
    name: 'Fitbit Charge 5',
    price: 129.95,
    inStock: false,
    category: 'Tech',
    tags: ['fitness', 'wearable'],
  },
  {
    name: 'Canon EOS M50 Camera',
    price: 649.99,
    inStock: false,
    category: 'Tech',
    tags: ['photography', 'camera'],
  },
  {
    name: 'Bose SoundLink Speaker',
    price: 129.0,
    inStock: false,
    category: 'Tech',
    tags: ['audio', 'bluetooth'],
  },
  {
    name: 'New Balance Running Shorts',
    price: 35.0,
    inStock: false,
    category: 'Sportswear',
    tags: ['shorts', 'running'],
  },
  {
    name: 'Garmin Forerunner 245',
    price: 299.99,
    inStock: false,
    category: 'Tech',
    tags: ['gps', 'smartwatch'],
  },
  {
    name: 'Puma Training Shoes',
    price: 79.99,
    inStock: true,
    category: 'Sportswear',
    tags: ['shoes', 'training'],
  },
  {
    name: 'HP Envy Printer',
    price: 159.99,
    inStock: true,
    category: 'Tech',
    tags: ['printer', 'office'],
  },
  {
    name: 'Spalding NBA Basketball',
    price: 29.99,
    inStock: true,
    category: 'Sports',
    tags: ['basketball', 'indoor'],
  },
  {
    name: 'Anker Portable Charger',
    price: 49.99,
    inStock: false,
    category: 'Tech',
    tags: ['charger', 'portable'],
  },
  {
    name: 'Reebok Gym Gloves',
    price: 19.99,
    inStock: false,
    category: 'Sportswear',
    tags: ['gloves', 'fitness'],
  },
  {
    name: 'Microsoft Surface Mouse',
    price: 49.99,
    inStock: true,
    category: 'Tech',
    tags: ['peripherals', 'mouse'],
  },
];

module.exports = { seedProducts };
